# Generated by Django 3.1.2 on 2020-10-28 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_method', models.CharField(choices=[('FREE_SAME_DAY_DRONE', 'FREE_SAME_DAY_DRONE'), ('FREE_TWO_DAY_TRUCK', 'FREE_TWO_DAY_TRUCK'), ('PREMIUM_SAME_DAY_TRUCK', 'PREMIUM_SAME_DAY_TRUCK'), ('PREMIUM_SAME_DAY_DRONE', 'PREMIUM_SAME_DAY_DRONE'), ('PREMIUM_TWO_DAY_TRUCK', 'PREMIUM_TWO_DAY_TRUCK')], max_length=128)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{5}$')])),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
