# Generated by Django 3.1.2 on 2020-11-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201115_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
