# Generated by Django 3.1.2 on 2020-10-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('FREE_SAME_DAY_DRONE', 'Free Same Day Drone'), ('FREE_TWO_DAY_TRUCK', 'Free Two Day Truck'), ('PREMIUM_SAME_DAY_TRUCK', 'Premium Same Day Truck'), ('PREMIUM_SAME_DAY_DRONE', 'Premium Same Day Drone'), ('PREMIUM_TWO_DAY_TRUCK', 'Premium Two Day Truck')], max_length=128),
        ),
    ]
