# Generated by Django 3.1.2 on 2020-10-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201023_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
    ]
