# Generated by Django 3.1.2 on 2020-11-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_location',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('PICKUP_1', 'Pickup 1'), ('PICKUP_2', 'Pickup 2'), ('FREE_SAME_DAY_DRONE', 'Free Same Day Drone'), ('COST_SAME_DAY_DRONE', 'Cost Same Day Drone'), ('FREE_TWO_DAY_TRUCK', 'Free Two Day Truck'), ('COST_SAME_DAY_TRUCK', 'Cost Same Day Truck'), ('COST_TWO_DAY_TRUCK', 'Cost Two Day Truck')], max_length=128),
        ),
    ]
