# Generated by Django 3.1.2 on 2020-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201118_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
