# Generated by Django 3.1.2 on 2020-10-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
