# Generated by Django 3.1.2 on 2020-10-23 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201023_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{5}$')]),
        ),
    ]
