# Generated by Django 3.1.2 on 2020-10-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201023_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('FREE_SAME_DAY_DRONE', 'FREE_SAME_DAY_DRONE'), ('FREE_TWO_DAY_TRUCK', 'FREE_TWO_DAY_TRUCK'), ('PREMIUM_SAME_DAY_TRUCK', 'PREMIUM_SAME_DAY_TRUCK'), ('PREMIUM_SAME_DAY_DRONE', 'PREMIUM_SAME_DAY_DRONE'), ('PREMIUM_TWO_DAY_TRUCK', 'PREMIUM_TWO_DAY_TRUCK')], max_length=128),
        ),
    ]
