# Generated by Django 3.1.2 on 2020-10-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201023_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
    ]
