# Generated by Django 3.1.2 on 2020-12-04 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201204_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(regex="^[a-zA-Z][a-zA-Z ,.'-]*$")]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(regex="^[a-zA-Z][a-zA-Z ,.'-]*$")]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
