# Generated by Django 3.1.2 on 2020-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.FloatField()),
                ('img_url', models.URLField()),
                ('category', models.CharField(choices=[('OFFICE_SUPPLIES', 'Office Supplies'), ('FURNITURE', 'Furniture'), ('CLEANING', 'Cleaning'), ('BREAKROOM', 'Breakroom'), ('COMPUTERS_ACCESSORIES', 'Computers Accessories'), ('ELECTRONICS', 'Electronics'), ('PAPERS', 'Papers'), ('SCHOOL_SUPPLIES', 'School Supplies'), ('INK_TONER', 'Ink Toner'), ('ETC', 'Etc')], max_length=128)),
                ('subcategory', models.CharField(choices=[('PENS_PENCILS_MARKERS', 'Pens Pencils Markers'), ('BASIC_SUPPLIES', 'Basic Supplies'), ('MAILING_SHIPPING', 'Mailing Shipping'), ('FILING_FOLDERS', 'Filing Folders'), ('BINDERS_ACCESSORIES', 'Binders Accessories'), ('LABELS', 'Labels'), ('DESK_ACCESSORIES', 'Desk Accessories'), ('STORAGE', 'Storage'), ('CHAIRS_SEATING', 'Chairs Seating'), ('STORAGE_SOLUTIONS', 'Storage Solutions'), ('DESKS', 'Desks'), ('TABLES', 'Tables'), ('OFFICE_DECOR', 'Office Decor'), ('LAMPS_LIGHTING', 'Lamps Lighting'), ('CLEANING_SUPPLIES', 'Cleaning Supplies'), ('TRASH_CANS_BAGS', 'Trash Cans Bags'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('PAPER_PRODUCTS', 'Paper Products'), ('SOAPS_SANITIZERS', 'Soaps Sanitizers'), ('SAFETY_SECURITY', 'Safety Security'), ('CLEANING_TOOLS', 'Cleaning Tools'), ('AIR_FRESHENERS', 'Air Fresheners'), ('COFFEE_SUPPLIES', 'Coffee Supplies'), ('CUPS_PLATES_CUTLERY', 'Cups Plates Cutlery'), ('FRESH_FROZEN_FOOD', 'Fresh Frozen Food'), ('BEVERAGES', 'Beverages'), ('CANDY_SNACKS', 'Candy Snacks'), ('APPLIANCES', 'Appliances'), ('COMPUTERS', 'Computers'), ('SOFTWARE', 'Software'), ('DATA_STORAGE_MEDIA', 'Data Storage Media'), ('COMPUTER_ACCESSORIES', 'Computer Accessories'), ('PRINTERS_ACCESSORIES', 'Printers Accessories'), ('INCREASE_PRODUCTIVITY', 'Increase Productivity'), ('COMPUTER_COMPONENTS', 'Computer Components'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('PHONES_ACCESSORIES', 'Phones Accessories'), ('TVS_HOME_THEATER', 'Tvs Home Theater'), ('NETWORKING_CABLES', 'Networking Cables'), ('BATTIES_POWER_PROTECTION', 'Batties Power Protection'), ('AUDIO', 'Audio'), ('COPY_PRINTER_PAPER', 'Copy Printer Paper'), ('PHOTO_PRESENTATION', 'Photo Presentation'), ('NOTEBOOKS_PADS', 'Notebooks Pads'), ('POST_IT_STICKY_PAPER', 'Post It Sticky Paper'), ('ART_CRAFT_PAPER', 'Art Craft Paper'), ('FILLER_GRAPH_PAPER', 'Filler Graph Paper'), ('ARTS_CRAFTS', 'Arts Crafts'), ('ELECTRONICS', 'Electronics'), ('WRITING', 'Writing'), ('BACKPACKS_LUNCH_BAGS', 'Backpacks Lunch Bags'), ('FOLDERS_BINDERS', 'Folders Binders'), ('BASIC_SCHOOL_SUPPLIES', 'Basic School Supplies'), ('NOTEBOOKS_PAPER', 'Notebooks Paper'), ('ETC', 'Etc')], max_length=128)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
