# Generated by Django 3.1.2 on 2020-11-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.FloatField()),
                ('img_url', models.URLField()),
                ('category', models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Breakroom', 'Breakroom'), ('Computer Accessories', 'Computers Accessories'), ('Electronics', 'Electronics'), ('Paper', 'Paper'), ('School Supplies', 'School Supplies'), ('Ink and Toner', 'Ink Toner'), ('Etc', 'Etc')], max_length=128)),
                ('subcategory', models.CharField(blank=True, choices=[('Pens, Pencils and Markers', 'Pens Pencils Markers'), ('Basic Supplies', 'Basic Supplies'), ('Mailing and Shipping', 'Mailing Shipping'), ('Filing and Folders', 'Filing Folders'), ('Binders and Accessories', 'Binders Accessories'), ('Labels and Label Makers', 'Labels'), ('Desk Accessories', 'Desk Accessories'), ('Storage', 'Storage'), ('Chairs and Seating', 'Chairs Seating'), ('Storage Solutions', 'Storage Solutions'), ('Desks', 'Desks'), ('Tables', 'Tables'), ('Office Decor', 'Office Decor'), ('Lamps and Lighting', 'Lamps Lighting'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Trash Cans and Bags', 'Trash Cans Bags'), ('Medical Supplies', 'Medical Supplies'), ('Paper Products', 'Paper Products'), ('Soaps and Sanitizers', 'Soaps Sanitizers'), ('Safety and Security', 'Safety Security'), ('Cleaning Tools', 'Cleaning Tools'), ('Air Fresheners', 'Air Fresheners'), ('Coffee Supplies', 'Coffee Supplies'), ('Cups, Plates and Cutlery', 'Cups Plates Cutlery'), ('Fresh and Frozen Food', 'Fresh Frozen Food'), ('Beverages', 'Beverages'), ('Candy and Snacks', 'Candy Snacks'), ('Appliances', 'Appliances'), ('Computers', 'Computers'), ('Software', 'Software'), ('Data Storage and Media', 'Data Storage Media'), ('Computer Accessories', 'Computer Accessories'), ('Printers and Accessories', 'Printers Accessories'), ('Computer Components', 'Computer Components'), ('Office Equipment', 'Office Equipment'), ('Phones and Accessories', 'Phones Accessories'), ('TVs and Home Theater', 'Tvs Home Theater'), ('Networking and Cables', 'Networking Cables'), ('Batteries and Power Protection', 'Batties Power Protection'), ('Audio', 'Audio'), ('Copy and Printer Paper', 'Copy Printer Paper'), ('Photo and Presentation', 'Photo Presentation'), ('Notebooks and Pads', 'Notebooks Pads'), ('Post-It and Sticky Paper', 'Post It Sticky Paper'), ('Art and Craft Paper', 'Art Craft Paper'), ('Filler and Graph Paper', 'Filler Graph Paper'), ('Arts and Crafts', 'Arts Crafts'), ('School Electronics', 'School Electronics'), ('Writing', 'Writing'), ('Backpacks and Lunch Bags', 'Backpacks Lunch Bags'), ('Folders and Binders', 'Folders Binders'), ('Basic School Supplies', 'Basic School Supplies'), ('Notebooks and Paper', 'Notebooks Paper'), ('Etc', 'Etc')], max_length=128)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
