# Generated by Django 3.1.2 on 2020-11-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('FURNITURE', 'Furniture'), ('CLEANING', 'Cleaning'), ('BREAKROOM', 'Breakroom'), ('COMPUTERS_ACCESSORIES', 'Computers Accessories'), ('ELECTRONICS', 'Electronics'), ('PAPERS', 'Papers'), ('SCHOOL_SUPPLIES', 'School Supplies'), ('INK_TONER', 'Ink Toner'), ('ETC', 'Etc')], max_length=128),
        ),
    ]
