# Generated by Django 3.1.2 on 2020-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201102_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Breakroom', 'Breakroom'), ('Computer Accessories', 'Computers Accessories'), ('Electronics', 'Electronics'), ('Paper', 'Paper'), ('School Supplies', 'School Supplies'), ('Ink & Toner', 'Ink Toner'), ('Etc', 'Etc')], max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Pens, Pencils & Markers', 'Pens Pencils Markers'), ('Basic Supplies', 'Basic Supplies'), ('Mailing & Shipping', 'Mailing Shipping'), ('Filing & Folders', 'Filing Folders'), ('Binders & Accessories', 'Binders Accessories'), ('Labels & Label Makers', 'Labels'), ('Desk Accessories', 'Desk Accessories'), ('Storage', 'Storage'), ('Chairs & Seating', 'Chairs Seating'), ('Storage Solutions', 'Storage Solutions'), ('Desks', 'Desks'), ('Tables', 'Tables'), ('Office Decor', 'Office Decor'), ('Lamps & Lighting', 'Lamps Lighting'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Trash Cans & Bags', 'Trash Cans Bags'), ('Medical Supplies', 'Medical Supplies'), ('Paper Products', 'Paper Products'), ('Soaps & Sanitizers', 'Soaps Sanitizers'), ('Safety & Security', 'Safety Security'), ('Cleaning Tools', 'Cleaning Tools'), ('Air Fresheners', 'Air Fresheners'), ('Coffee Supplies', 'Coffee Supplies'), ('Cups, Plates & Cutlery', 'Cups Plates Cutlery'), ('Fresh & Frozen Food', 'Fresh Frozen Food'), ('Beverages', 'Beverages'), ('Candy & Snacks', 'Candy Snacks'), ('Appliances', 'Appliances'), ('Computers', 'Computers'), ('Software', 'Software'), ('Data Storage & Media', 'Data Storage Media'), ('Computer Accessories', 'Computer Accessories'), ('Printers & Accessories', 'Printers Accessories'), ('Computer Components', 'Computer Components'), ('Office Equipment', 'Office Equipment'), ('Phones & Accessories', 'Phones Accessories'), ('TVs & Home Theater', 'Tvs Home Theater'), ('Networking & Cables', 'Networking Cables'), ('Batteries & Power Protection', 'Batties Power Protection'), ('Audio', 'Audio'), ('Copy & Printer Paper', 'Copy Printer Paper'), ('Photo & Presentation', 'Photo Presentation'), ('Notebooks & Pads', 'Notebooks Pads'), ('Post-It & Sticky Paper', 'Post It Sticky Paper'), ('Art & Craft Paper', 'Art Craft Paper'), ('Filler & Graph Paper', 'Filler Graph Paper'), ('Arts & Crafts', 'Arts Crafts'), ('School Electronics', 'School Electronics'), ('Writing', 'Writing'), ('Backpacks & Lunch Bags', 'Backpacks Lunch Bags'), ('Folders & Binders', 'Folders Binders'), ('Basic School Supplies', 'Basic School Supplies'), ('Notebooks & Paper', 'Notebooks Paper'), ('Etc', 'Etc')], max_length=128),
        ),
    ]
