# Generated by Django 3.1.2 on 2020-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201102_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Breakroom', 'Breakroom'), ('Computer Accessories', 'Computers Accessories'), ('Electronics', 'Electronics'), ('Paper', 'Paper'), ('School Supplies', 'School Supplies'), ('Ink and Toner', 'Ink Toner'), ('Etc', 'Etc')], max_length=128),
        ),
    ]
